first push for review
JosephLarbi21/dream-house pull request #1
Opened 2023-05-07 21:14 UTC by joey2022-eng

# What?

#Why?

#How?

2023-05-08 16:45 UTC, Haywayaheadshot requested changes
Hi @joey2022-eng , 

You have done very well coming this far with this project! There are a lot of issues to fix but we will tackle them one at a time. 

- First of all, please re-organize your files. Take for example [this](https://www.youtube.com/watch?v=s_Ie_yh_4Co&list=PL0Zuz27SZ-6PA3nkkEAr91n4bK-NunwPU) video. If you skip to 2:14:40, you will realize on the left, all the files have been organized in their appropriate folders.

Please tackle this issue first

2023-05-08 16:47 UTC, Haywayaheadshot commented
@joey2022-eng Also, please note that if you do not understand anything, you can always ask. I will be available to reply under this thread.

2023-05-08 16:53 UTC, Haywayaheadshot commented on index.html
> +
Also, it is not a good practice to leave commented codes in a project. You can check out [this](https://www.w3schools.com/js/js_best_practices.asp) article to understand it more. 

Please delete all unused codes.

2023-05-10 06:18 UTC, joey2022-eng commented
> Hi @joey2022-eng ,
> 
> You have done very well coming this far with this project! There are a lot of issues to fix but we will tackle them one at a time.
> 
> * First of all, please re-organize your files. Take for example [this](https://www.youtube.com/watch?v=s_Ie_yh_4Co&list=PL0Zuz27SZ-6PA3nkkEAr91n4bK-NunwPU) video. If you skip to 2:14:40, you will realize on the left, all the files have been organized in their appropriate folders.
> 
> Please tackle this issue first

Please am done with the changes you ask me to do.
The only issue right now is how to commit and push

> Hi @joey2022-eng ,
> 
> You have done very well coming this far with this project! There are a lot of issues to fix but we will tackle them one at a time.
> 
> * First of all, please re-organize your files. Take for example [this](https://www.youtube.com/watch?v=s_Ie_yh_4Co&list=PL0Zuz27SZ-6PA3nkkEAr91n4bK-NunwPU) video. If you skip to 2:14:40, you will realize on the left, all the files have been organized in their appropriate folders.
> 
> Please tackle this issue first

Please am done with it.

2023-05-10 06:18 UTC, closed without merging

2023-05-10 06:19 UTC, joey2022-eng commented
> Hi @joey2022-eng ,
> 
> You have done very well coming this far with this project! There are a lot of issues to fix but we will tackle them one at a time.
> 
> * First of all, please re-organize your files. Take for example [this](https://www.youtube.com/watch?v=s_Ie_yh_4Co&list=PL0Zuz27SZ-6PA3nkkEAr91n4bK-NunwPU) video. If you skip to 2:14:40, you will realize on the left, all the files have been organized in their appropriate folders.
> 
> Please tackle this issue first

Please am done with the re-organization.

2023-05-10 06:20 UTC, joey2022-eng commented
Done re-organizing it